// вместо ** название действия
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_REQUEST_SUCCESS = "REGISTRATION_REQUEST_SUCCESS";
export const REGISTRATION_REQUEST_FAIL = "REGISTRATION_REQUEST_FAIL";

export const AUTH_USER = "AUTH_USER";
export const LOG_OUT = "LOG_OUT";
export const AUTO_LOG_IN ="AUTO_LOG_IN";
export const NEW_ARRIVAL_TO_THE_POCKET = "NEW_ARRIVAL_TO_THE_POCKET";



export const NEW_EXPENSE_FROM_THE_POCKET = "NEW_EXPENSE_FROM_THE_POCKET";
export const NEW_EXPENSE_FROM_THE_POCKET_REQUEST = "NEW_EXPENSE_FROM_THE_POCKET_REQUEST"
export const NEW_EXPENSE_FROM_THE_POCKET_REQUEST_SUCCESS = "NEW_EXPENSE_FROM_THE_POCKET_REQUEST_SUCCESS"
export const NEW_EXPENSE_FROM_THE_POCKET_REQUEST_FAIL = "NEW_EXPENSE_FROM_THE_POCKET_REQUEST_FAIL"




export const ADD_USER_PHOTO ="ADD_USER_PHOTO";
export const ADD_USER_PHOTO_SUCCESS= "ADD_USER_PHOTO_SUCCESS";
export const ADD_USER_PHOTO_FAIL = "ADD_USER_PHOTO_FAIL";
export const ADD_USER_PHOTO_RESET ="ADD_USER_PHOTO_RESET";





export const ADD_POCKET_TO_STORE = "ADD_POCKET_TO_STORE";

export const AUTH_GET_REQUEST = "AUTH_REQUEST";
export const AUTH_GET_REQUEST_SUCCESS = "AUTH_REQUEST_SUCCESS";
export const AUTH_GET_REQUEST_FAIL = "AUTH_REQUEST_FAIL";



export const GET_POCKETS_FROM_SERVER_REQUEST = "GET_POCKETS_FROM_SERVER_REQUEST";
export const GET_POCKETS_FROM_SERVER_REQUEST_SUCCESS = "GET_POCKETS_FROM_SERVER_REQUEST_SUCCESS";
export const GET_POCKETS_FROM_SERVER_REQUEST_FAIL = "GET_POCKETS_FROM_SERVER_REQUEST_FAIL";


export const ADD_USER_PHOTO_REQUEST = "ADD_USER_PHOTO_REQUEST";
export const ADD_USER_PHOTO_REQUEST_SUCCESS = "ADD_USER_PHOTO_REQUEST_SUCCESS";
export const ADD_USER_PHOTO_REQUEST_FAIL = "ADD_USER_PHOTO_REQUEST_FAIL";



export const GET_ENTRIES_FROM_SERVER_REQUEST ="GET_ENTRIES_FROM_SERVER_REQUEST"
export const GET_ENTRIES_FROM_SERVER_REQUEST_SUCCESS ="GET_ENTRIES_FROM_SERVER_REQUEST_SUCCESS"
export const GET_ENTRIES_FROM_SERVER_REQUEST_FAIL ="GET_ENTRIES_FROM_SERVER_REQUEST_FAIL"


export const POST_ENTRIES_FROM_SERVER_REQUEST ="POST_ENTRIES_FROM_SERVER_REQUEST"
export const POST_ENTRIES_FROM_SERVER_REQUEST_SUCCESS ="POST_ENTRIES_FROM_SERVER_REQUEST_SUCCESS"
export const POST_ENTRIES_FROM_SERVER_REQUEST_FAIL ="POST_ENTRIES_FROM_SERVER_REQUEST_FAIL"
export const  POST_NEW_ENTRIES = "POST_NEW_ENTRIES"


export const POST_NEW_ARRIVAL_REQUEST = "POST_NEW_ARRIVAL_REQUEST"
export const POST_NEW_ARRIVAL_REQUEST_SUCCESS = "POST_NEW_ARRIVAL_REQUEST_SUCCESS"
export const POST_NEW_ARRIVAL_REQUEST_FAIL = "POST_NEW_ARRIVAL_REQUEST_FAIL"




export const POST_POCKET_TO_SERVER_REQUEST = "POST_POCKET_TO_SERVER_REQUEST"
export const POST_POCKET_TO_SERVER_REQUEST_SUCCESS = "POST_POCKET_TO_SERVER_REQUEST_SUCCESS"
export const POST_POCKET_TO_SERVER_REQUEST_FAIL = "POST_POCKET_TO_SERVER_REQUEST_FAIL"

